### ISSUE TITLE
Create a release instead of the google drive link

### ISSUE THREAD

**Issue by nazmulhossainnihal** [dustyRAIN/Muffin-Waits#2]
Awesome extension! I have been using it for last few months. Can you guys make a Github Release instead of google drive link?
Tinyurl was blocked on my isp or something I had trouble downloading it. I guess it would be easier to download if you had a github release.

**Comment by dustyRAIN** [comment]
Thank you so much! Your suggestion made me realize that it was very naive of me not to make a release earlier. Thank you for your suggestion as well.

I've created a release just now. you can check it [here](https://github.com/dustyRAIN/Muffin-Waits/releases)
